# Spring Boot uygulamasının adını belirtir.
# Bu değer, özellikle dağıtık sistemlerde ve mikroservis mimarisinde
# servislerin birbirini tanıması için kullanılır.
# Spring Cloud, Service Discovery (Eureka), Actuator ve loglama süreçlerinde önemlidir.
spring.application.name=config_server

# Uygulamanın çalışacağı port numarasını belirtir.
# Spring Cloud Config Server için yaygın olarak 8888 portu kullanılır.
server.port=8888

# Varsayılan Spring Boot hata sayfasını (Whitelabel Error Page) devre dışı bırakır.
spring.web.error.whitelabel.enabled=false

# Config Server'ın konfigürasyon dosyalarını okuyacağı Git deposunun adresidir.
# Config Server, istemci uygulamaların yapılandırma dosyalarını bu depodan çeker.
# Eğer Git deposu private (özel) ise, kullanıcı adı ve Personal Access Token (PAT)
# gibi kimlik doğrulama bilgileri de tanımlanmalıdır.
spring.cloud.config.server.git.uri=https://github.com/oguzcanuzunoner/offline_microservis_2_config_server

# Config Server'ın kullanacağı varsayılan Git branch'ini belirtir.
# Eğer belirtilmezse genellikle "main" branch'i kullanılır.
# Farklı bir branch kullanıyorsanız aşağıdaki değeri güncelleyin.
spring.cloud.config.server.git.default-label=main

# Alternatif örnek:
# spring.cloud.config.server.git.default-label=master

# Config Server'ın Git deposu içerisinde konfigürasyon dosyalarını
# arayacağı dizini belirtir.
# Bu örnekte yapılandırma dosyaları "config-repo" klasörü altında bulunmaktadır.
spring.cloud.config.server.git.search-paths=config-repo